- name: minha primeira playbook
  hosts: devops docker
  tasks:
   - name: criando usuario
     user: 
      name: devops
      state: present
      password: '$1$VkncOzhJ$THR8taVI3hVJ/1nXy6aKl/'

   - name: instalando pacote na playbook
     package:
      name: vim

   - name: copiando um arquivo
     copy: 
      src: config.php
      dest: /tmp/
